### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#1]
### Tasks
- Create a landing page for new users which will give an overview of the website and its features. 
- The landing page should have an input field which will take the city or location of the user.
- After the user provides his/her location he/she should be redirected to the main info page.
- Create a user-friendly and mobile-responsive landing page.
- Do not try to complete the whole website in just one go.
- Follow the wireframe

## Wirefeame:
![image](https://github.com/user-attachments/assets/1869f4fc-5eb6-43e0-892e-a804107dafd0)

**Comment by raj-mistry-01** [comment]
Please Assign me this , I really want to work on this issue.

**Comment by Vatsal2054** [comment]
You can start working on it.

**Comment by Pragya79645** [comment]
Please assign this to me.

**Comment by Vatsal2054** [comment]
I have assigned this issue to @Pragya79645 . Create only landing page and no more.
The landing page will be the entry point of our website.
- You would work on index.html, styles.css and index.js only.

**Comment by nandit27** [comment]
@Vatsal2054 is it completed or else I can work on it ?

**Comment by Vatsal2054** [comment]
Remember to follow the wireframe. And give update in 24 hours.
