### ISSUE TITLE
Creating Forecast cards in wether_info.html

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#13]
### Task:
Create weather info cards which will be used to display 5-day forecasts.

- Work only with HTML and CSS.(weather_info.html and style.css).
- Insert dummy data for now.
- Create 5 cards in the forecast section according to the following wireframe. 
- You can tweak the design but try to contain all the information given in the wireframe.
- You are free to add more info in the card.
- Make sure the cards matches the theme.

![image](https://github.com/user-attachments/assets/32af7a71-9c83-4e4e-9c39-57d6a8e375d4)

**Comment by Vatsal2054** [comment]
Make sure to follow the instructions and do not change index.js. Provide follow up as soon as possible.

**Comment by Meetpidev** [comment]
is it still an issue ? or solved it ?

**Comment by Vatsal2054** [comment]
It has been solved now...
