### ISSUE TITLE
Show realtime forecast info in the forecast cards.

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#17]
## Task:
- Update JavaScript in index.js to replace the dummy data in the forecast cards with realtime forecast info.
- Work only with index.js and weather_info.html
- Update icons according to weather status.

**Comment by nandit27** [comment]
@Vatsal2054 I want to work on this.

**Comment by Meetpidev** [comment]
@Vatsal2054 can u assign me this task ?

**Comment by Vatsal2054** [comment]
@nandit27 There are bugs in the index.js file which need to be solved before working on this issue. Can you do that?

**Comment by Vatsal2054** [comment]
@git112 @Meetpidev I am sorry for late replies but there were some things which needed to be taken care of before assigning this issue to anyone. I am following first come first serve rule. I hope you guys understand.
