### ISSUE TITLE
New Idea To Project - Weather Web App

### ISSUE THREAD

**Issue by raj-mistry-01** [clubgamma/Weather-Web-App-2024#2]
I want to add react js , along with html , css and Js  in the landing page issue , so that the technology used for this project is enhanced 

Further I can integrate it to real time + full stack web app project.

Please Assign this issue to me.

**Comment by Vatsal2054** [comment]
Nice Idea. I will assign you this issue but you must complete some assignments:

## Tasks
- Initialize vite+react project.
- Create file structure for react which is capable for scalability in the future.
- Try to keep the existing files in your new structure. 
- Log updations of this issue daily.

### Important: Create the file structure which will not result in conflicts or error during PR.


You are good to go!

**Comment by raj-mistry-01** [comment]
Thank you for assigning me  this Issue , Tomorrow I will tell you the features of website , I will need at least 5 days to built it.

Thank you
