### ISSUE TITLE
Better User Experience 

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Weather-Web-App-2024#22]
We have to scroll to see all the information that is not good user experience..

**Comment by Meetpidev** [comment]
can i work on this ?

**Comment by Vatsal2054** [comment]
If you are confident that you can improve UI, you can work on it. But work only with HTML and CSS. Do not tweak javascript.

**Comment by Meetpidev** [comment]
@Vatsal2054 Can i use bootstrap ??

**Comment by Vatsal2054** [comment]
You can. Just make sure it doesn't create a confilct with existing files.

**Comment by vasu-CE** [comment]
@Vatsal2054 can i work on this

**Comment by Vatsal2054** [comment]
@vasu-CE You can but I will only accept your updated UI if it is better than the current UI.
