### ISSUE TITLE
Fix inconsistent font sizes in Landing page and weather info page

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#34]
## Task
- Fix inconsistent font sizes in landing page. E.g:
  - Copyright text in Landing page and weather info page
  - City name in weather info page
- Add icon in search button

**Comment by Vatsal2054** [comment]
@Meetpidev You are already working on 2 issues. So, try to create a single PR for all assigned issues.

**Comment by vasu-CE** [comment]
assign

**Comment by Vatsal2054** [comment]
@vasu-CE I have already assigned this issue to @Meetpidev as he is currently woking on UI. You can work on any new Issues when created.
