### ISSUE TITLE
Separate CSS files for landing page and wheather information page..

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Weather-Web-App-2024#39]
### There should be separate CSS file for whether information page..

**Comment by Vatsal2054** [comment]
Ok, you can work on it.

**Comment by Meetpidev** [comment]
@Vatsal2054 I will make separate file for the style of whether information page.. in that file only that page's style in included.. so its easy to make changes..

**Comment by Vatsal2054** [comment]
What about adding Bootstrap for UI? Are you working on that?

**Comment by Meetpidev** [comment]
> What about adding Bootstrap for UI? Are you working on that?

yes im working on that..
