### ISSUE TITLE
text inside forecast card not aligned

### ISSUE THREAD

**Issue by Aryanbhargava18** [clubgamma/Weather-Web-App-2024#40]

**Comment by Vatsal2054** [comment]
@Aryanbhargava18 You can also try to improve the overall UI of the forecast cards.

**Comment by Aryanbhargava18** [comment]
@Vatsal2054 i will try to do that.

**Comment by Vatsal2054** [comment]
@Aryanbhargava18 Any updates??

**Comment by Aryanbhargava18** [comment]
@Vatsal2054 check now.
