### ISSUE TITLE
Feature Request: Add Wind Speed and Humidity to Weather Data

### ISSUE THREAD

**Issue by hival01** [clubgamma/Weather-Web-App-2024#43]
The current weather data only displays temperature. To provide more comprehensive information, it would be beneficial to include wind speed and humidity in the app as well.

**Comment by Vatsal2054** [comment]
@hival01 Can you work on that?

**Comment by vasu-CE** [comment]
assign

**Comment by hival01** [comment]
@Vatsal2054 sure i will work on that

**Comment by Meetpidev** [comment]
@Vatsal2054 Can I Work On This ??

**Comment by Vatsal2054** [comment]
@Meetpidev This issue has already been assigned to @hival01.

**Comment by Vatsal2054** [comment]
@hival01 Any updates??
