### ISSUE TITLE
Other Projects of Club-gamma 

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Weather-Web-App-2024#45]
### They can get all the information in README.md file about all the projects that is under club-gamma..

**Comment by Meetpidev** [comment]
@Vatsal2054 Can i do this ?

**Comment by Meetpidev** [comment]
@Vatsal2054 Can i do this ?

**Comment by Vatsal2054** [comment]
The information about projects is available on the club gamma website. No need to work on that
