### ISSUE TITLE
Create weather info page (HTML, CSS only)

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#5]
### The page should have following components:
- A header containing city name and current date with week day and a button to change city.
- A section to display current weather info.
- A section for forecasts.
- A section for rain and humidity information.
- A footer

## Instructions:
- Only work on the UI of the page. For each info field give a unique ID which will be used to display data dynamically.
- Try to make the page as user-friendly as possible.
- The theme should follow a specific color palette.

## IMP
- This assignment is only for the UI of the page. Do NOT update the logic in the index.js.

**Comment by nandit27** [comment]
@Vatsal2054 can u assign this to me ?

**Comment by nandit27** [comment]
Do you want like this way or every info on the same page ? @Vatsal2054 
<img width="982" alt="Screenshot 2024-10-19 at 9 17 37 AM" src="https://github.com/user-attachments/assets/12b6cab4-3ccc-446e-be73-18ff26330618">

**Comment by Vatsal2054** [comment]
This layout is good. It should contain enogh info and try to add some icons, illustrations or visual media if you can :)

**Comment by nandit27** [comment]
The thing is that when you click on current weather it will show necessary info and similarly for each button. So is this okay ?
I will add the icons and all necessary things.
