### ISSUE TITLE
Add event listeners for better User Experience

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#56]
## Tasks:
- Add feature to access search suggestions using up/down keys of keyboard from the search bar. i.e User should be able to access the first suggestion item from the search input using down arrow key.
- Selecting a suggestion should initiate search for that suggested location.
- Display the suuggestion bar directly below the search field above other items in the search box.

![image](https://github.com/user-attachments/assets/1f4b5407-d1c5-4e64-bb00-99b846e52a99)

**Comment by vasu-CE** [comment]
assign to me
