### ISSUE TITLE
Logic for the weather info page (JavaScript only)

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#6]
## Tasks:
-  Access user location obtained from landing page.
- Fetch weather info from any open-source weather API provider based on the location e.g. [Open Weather Map](https://openweathermap.org/).
- Store the weather data in a javascript object.
- Access the input fields in the info page. Use jQuery if possible.
- Update the weather information on the info page.

**Comment by PriyanshuValiya** [comment]
@Vatsal2054 Please assign me this issue under hacktoberfest.

**Comment by Vatsal2054** [comment]
Provide follow up as soon as possible.

**Comment by PriyanshuValiya** [comment]
Ok

**Comment by nandit27** [comment]
Is the work done ? Or I can work on it ? @Vatsal2054

**Comment by PriyanshuValiya** [comment]
@nandit27 I am working on it and it's almost completed..

**Comment by nandit27** [comment]
@PriyanshuValiya is the work done ?

**Comment by PriyanshuValiya** [comment]
@nandit27 Yes and also branch has been merged..

**Comment by nandit27** [comment]
No, no data is visible whenever we enter any city name. And also no forecast is also visible. Means fields remain as it is when we enter the city name.

**Comment by Vatsal2054** [comment]
Data is being displayed in the current deployed site. I will be creating a new issue today. @nandit27 You are free to work on that.
