### ISSUE TITLE
IMP - Adding contributors to the CONTRIBUTING.md

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#67]
## To every contributor of this project, please comment the following info which will be added in the CONTRIBUTING.md file

- Place: City, State, Country
- Bio: Who are you?
- GitHub: [GitHub account name](GitHub link) 

### It is mandatory if you want to be recognized as an official contributor.

@hival01 @PriyanshuValiya @Meetpidev @git112 @vasu-CE @soni-shashan @Agnish1611 @nandit27 @Uvesh99 @Ayushkalathiya

**Comment by Meetpidev** [comment]
Place: Rajkot, Gujarat, India.
Bio: Hello! I'm Meet Shah, a web development specialist with expertise in the MERN stack and Next.js. My focus is on building dynamic, user-centric web applications that prioritize both functionality and a seamless user experience.
GitHub: https://github.com/Meetpidev

**Comment by Meetpidev** [comment]
Place: Rajkot, Gujarat, India.
Bio: Hello! I'm Meet Shah, a web development specialist with expertise in the MERN stack and Next.js. My focus is on building dynamic, user-centric web applications that prioritize both functionality and a seamless user experience.
GitHub: https://github.com/Meetpidev

**Comment by nandit27** [comment]
Place: Gandhinagar, Gujarat, India
Bio: I'm Nandit Kalaria. I am an inspiring web developer skilled in ReactJS, with a passion for building creating user-focused applications. I enjoy combining technologies and design, exploring everything from frontend to chatbot reaction.
GitHub: nandit27 [https://github.com/nandit27]

**Comment by Uvesh99** [comment]
Place: Balasinor, Gujarat, India
Bio: I'm Saiyad Uveshali , a Full Stack Developer and Machine Learning Enthusiast with expertise in end-to-end web applications and intelligent data solutions.
GitHub: Uvesh99 https://github.com/Uvesh99

**Comment by PriyanshuValiya** [comment]
Place :  Surat, Gujarat, India
Bio : I am Priyanshu Valiya, I am MERN Stack enthusiast and passionate about building a SaaS applications. 
GitHub : PriyanshuValiya - https://github.com/PriyanshuValiya

**Comment by soni-shashan** [comment]
Place:  **Bhavanagar, Gujarat, India**🌍 
Bio 🎓: I am **Shashan Lumbhani**, a B.Tech Computer Science student at CSPIT, graduating in 2027, specializing in software development. I actively contribute to projects involving **web development**, **real-time systems**, and **algorithms**. An enthusiastic GitHub contributor, I showcase skills in various programming languages and technologies.
**GitHub** : **[soni-shashan](https://github.com/soni-shashan/)**

**Comment by Agnish1611** [comment]
Place: Kolkata, West Bengal, India
Bio: Hello! I'm Agnish Bhattacharya, an aspiring software developer, currently proficient in MERN stack and Next Js, and learning DevOps
GitHub: https://github.com/Agnish1611

**Comment by vasu-CE** [comment]
Place: Jetpur , Gujarat , India
Bio :  Second-year CE student at CSPIT, focused on building skills in Web Development.
GitHub : https://github.com/vasu-CE
