### ISSUE TITLE
Chance of rain

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Weather-Web-App-2024#68]
Display chance of rain based on city

**Comment by Meetpidev** [comment]
@Vatsal2054 Can i work on this ?

**Comment by Meetpidev** [comment]
@Vatsal2054 Requested to assign me

**Comment by Meetpidev** [comment]
@Vatsal2054 Can I Work On This ?

**Comment by Vatsal2054** [comment]
@Meetpidev YOu can work on it.
