### ISSUE TITLE
BUG: Weather info not being displayed

### ISSUE THREAD

**Issue by Vatsal2054** [clubgamma/Weather-Web-App-2024#76]
## After the merging recent PR by @PriyanshuValiya, the weather info is not being reflected in the forecast cards. @PriyanshuValiya, can you look into it?

**Comment by PriyanshuValiya** [comment]
I will look it..

**Comment by Vatsal2054** [comment]
@PriyanshuValiya Another contributor has solved it. No need for you to do it. Thanks for quick response.
