### ISSUE TITLE
Improve : Complete project level up by nextjs

### ISSUE THREAD

**Issue by Adeesh-bode** [clubgamma/Weather-Web-App-2024#8]
More suitable for further development,

**Comment by Adeesh-bode** [comment]
It is scalabity feature , I dont understand , why it is not planned , coz it wont hamper existing code of yours

**Comment by Vatsal2054** [comment]
As a part of Hacktoberfest 2024, this project was initially planned to be made with HTML, CSS and JavaScript only for Juniors who do not have experience with JavaScript frameworks.
Your idea was valid but it would increase the difficulty of this project.

**Comment by Adeesh-bode** [comment]
oh! Got it , No Worries!
